# Generated by Django 3.2.15 on 2022-09-09 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Имя экстренной службы')),
                ('service_code', models.IntegerField(verbose_name='Код экстренной службы')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон экстренной службы')),
            ],
            options={
                'verbose_name': 'Экстренная служба',
                'verbose_name_plural': 'Экстренные службы',
                'ordering': ('-service_code',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Номер карточки')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('injured', models.IntegerField(verbose_name='Количество пострадавших')),
                ('do_not_call', models.CharField(max_length=255, verbose_name='Не звонить')),
                ('status', models.CharField(choices=[('Male', 'В работе'), ('Female', 'Завершено')], default='Male', max_length=255, verbose_name='Статус')),
                ('emergency_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='emergency_request.emergencyservice', verbose_name='Экстренная служба')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ('-request_number', '-request_date'),
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя заявителя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия заявителя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество заявителя')),
                ('birthdate', models.DateField(verbose_name='Дата рождения заявителя')),
                ('health_status', models.TextField(blank=True, default='Практически здоров', help_text='аллергоанамез, хроническе, заболевания и т.п.', max_length=255, verbose_name='Состояние здоровья')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='Телефон заявителя')),
                ('gender', models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], max_length=255, verbose_name='Пол')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображения заявителя', upload_to='photos/applicants/%Y/%m/%d', verbose_name='Изображение заявителя')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='emergency_request.request', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ('-first_name',),
            },
        ),
    ]
