# Generated by Django 4.1.1 on 2022-11-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
