# Generated by Django 4.1.1 on 2022-10-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
        migrations.AlterModelOptions(
            name='emergencyservice',
            options={'verbose_name': 'Экстренная служба', 'verbose_name_plural': 'Экстренные службы'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
    ]
