# Generated by Django 4.1.1 on 2022-11-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте изображения заявителя', upload_to='photos/applicants/%Y/%m/%d', verbose_name='Изображение заявителя'),
        ),
    ]
